server:
  port: 8081
  servlet:
    context-path: /api

spring:
  profiles:
    active: local
  liquibase:
      enabled: true
      change-log: classpath:db/changelog/changelog.yaml
  datasource:
    url: jdbc:mysql://localhost:3306/event_alert?allowMultiQueries=true
    username: event_alert_user
    password: 1234qwer
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        use_sql_comments: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

app:
  security:
    secret: "SecretKeyToGenerateJWTs"
    access-token-expiration-time: 3600000 # 1 hour
    refresh-token-expiration-time: 2592000000 # 30 days
    access-token-id: "AccessTokenId"
    refresh-token-id: "RefreshTokenId"
    token-prefix: "Bearer "
    auth-header: "Authorization"
    auth-register-url: "/auth/register"
    auth-login-url: "/auth/login"
  notification:
    enabled: false # Credentials must be set in firebase-service-account.json in order to connect to Firebase
    event-id-key: "eventId"
    event-date-time-key: "eventDateTime"
    event-tag-name-key: "eventTagName"
    event-tag-image-path-key: "eventTagImagePath"
    event-severity-name-key: "eventSeverityName"
    event-severity-color-key: "eventSeverityColor"
    event-latitude-key: "eventLatitude"
    event-longitude-key: "eventLongitude"
