server:
  port: 8081
  servlet:
    context-path: /api

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/event_alert
    username: event_alert_user
    password: 1234qwer
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        use_sql_comments: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

# Credentials must be set in firebase-service-account.json in order to connect to Firebase
app:
  notification:
    enabled: false
